# Generated by Django 5.2 on 2025-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('rate_to_usd', models.FloatField(help_text='Exchange rate to 1 USD')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
